[providers]
python = "3.9"

[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install -e ."]

[phases.build]
cmds = ["echo 'Python project - no build needed'"]

[start]
cmd = "python app.py"