name: Advanced Spacenations Deployment

on:
  push:
    branches: [ main ]
    
env:
  SITE_URL: https://${{ github.repository_owner }}.github.io/Spacenations-tools

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 🔍 Code Quality Checks
      run: |
        echo "🔍 Running quality checks..."
        
        # Check for common issues
        if grep -r "console.log" *.html; then
          echo "⚠️ Warning: console.log found in production code"
        fi
        
        # Check for placeholder texts
        if grep -r "PLACEHOLDER\|TODO\|FIXME" *.html; then
          echo "⚠️ Warning: Placeholder text found"
        fi
        
        # Check file sizes
        for file in *.html; do
          if [ -f "$file" ]; then
            size=$(stat -c%s "$file" 2>/dev/null || wc -c < "$file")
            echo "📄 $file: ${size} bytes"
            if [ $size -gt 100000 ]; then
              echo "⚠️ Warning: $file is quite large (${size} bytes)"
            fi
          fi
        done

  deploy:
    needs: quality-checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 🚀 Skip Deploy (handled by deploy-branches.yml)
      run: |
        echo "🔄 Deployment is handled by deploy-branches.yml workflow"
        echo "✅ This workflow focuses on quality checks only"
        
    - name: 🌐 Deployment Info
      run: |
        echo "📊 Quality checks completed successfully"
        echo "🔗 Site will be available at: $SITE_URL"
        echo "📝 Commit: ${{ github.sha }}"

  notify:
    needs: [quality-checks, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: 📢 Deployment Status
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "🎉 Spacenations Tools successfully deployed!"
          echo "🔗 URL: $SITE_URL"
          echo "📝 Commit: ${{ github.sha }}"
          echo "👤 Author: ${{ github.actor }}"
        else
          echo "❌ Deployment failed!"
        fi
