name: Advanced Spacenations Deployment

on:
  push:
    branches: [ main ]
    
env:
  SITE_URL: https://${{ github.repository_owner }}.github.io/Spacenations-tools

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 🔍 Code Quality Checks
      run: |
        echo "🔍 Running quality checks..."
        
        # Check for common issues
        if grep -r "console.log" *.html; then
          echo "⚠️ Warning: console.log found in production code"
        fi
        
        # Check for placeholder texts
        if grep -r "PLACEHOLDER\|TODO\|FIXME" *.html; then
          echo "⚠️ Warning: Placeholder text found"
        fi
        
        # Check file sizes
        for file in *.html; do
          size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file")
          echo "📄 $file: ${size} bytes"
          if [ $size -gt 100000 ]; then
            echo "⚠️ Warning: $file is quite large (${size} bytes)"
          fi
        done

  deploy:
    needs: quality-checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: 🚀 Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        commit_message: 🚀 Deploy ${{ github.sha }}
        
    - name: 🌐 Test Deployment
      run: |
        echo "⏳ Waiting for deployment..."
        sleep 30
        
        # Test if site is accessible
        if curl -f -s "$SITE_URL" > /dev/null; then
          echo "✅ Site is live and accessible!"
        else
          echo "❌ Site might not be accessible yet"
        fi

  notify:
    needs: [quality-checks, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
    - name: 📢 Deployment Status
      run: |
        if [ "${{ needs.deploy.result }}" == "success" ]; then
          echo "🎉 Spacenations Tools successfully deployed!"
          echo "🔗 URL: $SITE_URL"
          echo "📝 Commit: ${{ github.sha }}"
          echo "👤 Author: ${{ github.actor }}"
        else
          echo "❌ Deployment failed!"
        fi
